import streamlit as st
import time

# --- OTURUM DURUMU (SESSION STATE) BAŞLANGIÇ AYARLARI ---
ADMIN_PASSWORD = "123"
# ...
if 'admin_mode' not in st.session_state:
# ...
def user_login(username, password):
# ...
if not st.session_state['admin_mode']:
# ...
